// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zinyvsplazwfgmwcvrpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inppbnl2c3BsYXp3Zmdtd2N2cnBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTUzMzIsImV4cCI6MjA3MDE3MTMzMn0.d5pDvhwZJkjIwpmq1JA8KGgzShwDuWC4ptfSeT2axmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});